services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_crawler
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: DataCrawler
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - crawler_network

volumes:
  mongodb_data:
    name: mongodb_crawler_data

networks:
  crawler_network:
    name: crawler_network
