

openapi: "3.0.0"
info:
  version: 1.0.0
  title: template
  license:
    name: MIT
servers:
  - url: http://localhost:8080
    description: Local server
  - url: https://api.example.com/v1
    description: Production server
paths:
  /api/actuator/health:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Status of the service
                    example: UP
components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
          description: Error code
        message:
          type: string
          description: Error message
        fields:
          type: string
          description: Fields with errors
        
