package commons

import "time"

const (
	// ROLES
	ROLE_ADMIN = "admin"
	ROLE_USER  = "user"

	// ACTIVITY TYPES
	ACTIVITY_LOGIN     = "LOGIN"
	ACTIVITY_LOGOUT    = "LOGOUT"
	ACTIVITY_CHECK_IN  = "CHECK_IN"
	ACTIVITY_CHECK_OUT = "CHECK_OUT"
	ACTIVITY_EXPORT    = "EXPORT"

	// ATTENDANCE STATUS
	ATTENDANCE_ABSENT     int32 = 0
	ATTENDANCE_PRESENT    int32 = 1
	ATTENDANCE_PERMISSION int32 = 2
	ATTENDANCE_SICK       int32 = 3

	// DEFAULT VALUE
	USER_SYSTEN  = "SYSTEM"
	REDIS_EXPIRY = 5 * time.Minute

	// REDIS KEY
	REDIS_KEY = "LOGIN|USER|"
)
